In [79]:
import numpy as np
import itertools
from matplotlib import pyplot as plt
rng = np.random.default_rng()
epochs = 50000

k = 15  # total units
N = 5   # number of bins

dictionary = []
# weak compositions of k into N parts
for dividers in itertools.combinations(range(k + N - 1), N - 1):
    # compute sizes from adjacent divider positions
    prev = -1
    vec = []
    for d in dividers:
        vec.append(d - prev - 1)
        prev = d
    vec.append(k + N - 1 - prev - 1)
    dictionary.append(vec)
n = len(dictionary)
dictionary = np.array(dictionary)
batch = 100
#graph  = [[] for _ in range(n)]
strategy = np.ones(n) / n
cumulative_regret = np.zeros(n)

def normalformgame(idt, idc):
    t = dictionary[idt]
    c = dictionary[idc]
    return np.sum((t > c) )#* np.arange(1, N + 1))

def regretcalculation(idc):
    counterfactual_scores = np.sum((dictionary > idc)) #* np.arange(1, N + 1), axis=1)
    regrets = np.maximum(0, counterfactual_scores)
    return regrets
def sample_action(strategy):
    r = np.random.random()
    cum = np.cumsum(strategy)
    return np.searchsorted(cum, r)

In [14]:
!pip install tqdm

In [80]:
from tqdm import tqdm
for i in tqdm(range(epochs)):
    positive_regret = np.maximum(cumulative_regret, 0)
    total = positive_regret.sum()
    if total > 0:
        strategy = positive_regret / total
    else:
        strategy = np.ones(n) / n

    # for g in range(bat ch):
    action_old = rng.choice(dictionary, size=1, p=strategy)
    regrets = regretcalculation(action_old[0])
    cumulative_regret += regrets #* (1 / (i+1))
    #for j in range (n):
     #graph[j].append(strategy[j])
    # print(i)
print(strategy)
winning = np.argmax(strategy)
winningvalue = np.max(strategy)
averagedistribution = strategy @ dictionary
print(averagedistribution)
print(winningvalue)
print(dictionary[winning])
#plt.xscale('log')
#for m in range(n):
    #plt.plot(graph[m])
#plt.show()

100%|██████████| 50000/50000 [00:08<00:00, 6183.58it/s]

[0.000258 0.000258 0.000258 ... 0.000258 0.000258 0.000258]
[3. 3. 3. 3. 3.]
0.00025799793601651185
[ 0  0  0  0 15]


In [85]:
action = rng.choice(dictionary, size=1, p=strategy)
print(action[0])

[3 1 4 0 7]


In [87]:
rounds = 50000
total = 0

input1 = 1
input2 = 2
input3 = 3
input4 = 4
input5 = 5

t = np.array([input1, input2, input3, input4, input5])

for i in range(rounds):
  action = rng.choice(dictionary, size=1, p=strategy)
  score = np.sum((t > action[0]))
  opponent = np.sum((t < action[0]))

  total += (score - opponent)

print("Net AVG: " + str(total / rounds))



Net AVG: 0.64504
